/* Copyright (c) 2019, BOXEVER Ltd. info@boxever.com
 * 
 * Permission to use, copy, modify, and/or distribute this software for any 
 * purpose with or without fee is hereby granted, provided that the above 
 * copyright notice and this permission notice appear in all copies, unless
 * agreed otherwise.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH 
 * REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY 
 * AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, 
 * INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM 
 * LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE 
 * OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR 
 * PERFORMANCE OF THIS SOFTWARE.
 */
var __JSON;__JSON||(__JSON={});
(function(){function a(a){return 10>a?"0"+a:a}function b(a){g.lastIndex=0;return g.test(a)?'"'+a.replace(g,function(a){var d=o[a];return"string"===typeof d?d:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,p){var d,e,f,g,o=i,l,n=p[a];n&&("object"===typeof n&&"function"===typeof n.to__JSON)&&(n=n.to__JSON(a));"function"===typeof j&&(n=j.call(p,a,n));switch(typeof n){case "string":return b(n);case "number":return isFinite(n)?String(n):"null";case "boolean":case "null":return String(n);
case "object":if(!n)return"null";i+=m;l=[];if("[object Array]"===Object.prototype.toString.apply(n)){g=n.length;for(d=0;d<g;d+=1)l[d]=c(d,n)||"null";f=0===l.length?"[]":i?"[\n"+i+l.join(",\n"+i)+"\n"+o+"]":"["+l.join(",")+"]";i=o;return f}if(j&&"object"===typeof j){g=j.length;for(d=0;d<g;d+=1)"string"===typeof j[d]&&(e=j[d],(f=c(e,n))&&l.push(b(e)+(i?": ":":")+f))}else for(e in n)Object.prototype.hasOwnProperty.call(n,e)&&(f=c(e,n))&&l.push(b(e)+(i?": ":":")+f);f=0===l.length?"{}":i?"{\n"+i+l.join(",\n"+
i)+"\n"+o+"}":"{"+l.join(",")+"}";i=o;return f}}"function"!==typeof Date.prototype.to__JSON&&(Date.prototype.to__JSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.to__JSON=Number.prototype.to__JSON=Boolean.prototype.to__JSON=function(){return this.valueOf()});var e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,i,m,o={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},j;"function"!==typeof __JSON.stringify&&(__JSON.stringify=function(a,b,d){var e;m=i="";if(typeof d==="number")for(e=0;e<d;e=e+1)m=m+" ";else typeof d==="string"&&(m=d);if((j=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("__JSON.stringify");return c("",
{"":a})});"function"!==typeof __JSON.parse&&(__JSON.parse=function(a,b){function d(a,c){var e,h,j=a[c];if(j&&typeof j==="object")for(e in j)if(Object.prototype.hasOwnProperty.call(j,e)){h=d(j,e);h!==void 0?j[e]=h:delete j[e]}return b.call(a,c,j)}var c,a=String(a);e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){c=eval("("+a+")");return typeof b==="function"?d({"":c},""):c}throw new SyntaxError("__JSON.parse");})})();var BoxeverStorage=BoxeverStorage||{};
(function(){function a(){var a="{}";if("userDataBehavior"==q){f.load("bStorage");try{a=f.getAttribute("bStorage")}catch(d){}try{r=f.getAttribute("bStorage_update")}catch(b){}k.bStorage=a}g();o();j()}function b(){var t;clearTimeout(n);n=setTimeout(function(){if("localStorage"==q||"globalStorage"==q)t=k.bStorage_update;else if("userDataBehavior"==q){f.load("bStorage");try{t=f.getAttribute("bStorage_update")}catch(b){}}if(t&&t!=r){r=t;var j=p.parse(p.stringify(d.__bstorage_meta.CRC32)),e;a();e=p.parse(p.stringify(d.__bstorage_meta.CRC32));
var h,g=[],i=[];for(h in j)j.hasOwnProperty(h)&&(e[h]?j[h]!=e[h]&&"2."==String(j[h]).substr(0,2)&&g.push(h):i.push(h));for(h in e)e.hasOwnProperty(h)&&(j[h]||g.push(h));c(g,"updated");c(i,"deleted")}},25)}function c(a,d){a=[].concat(a||[]);if("flushed"==d){var a=[],b;for(b in l)l.hasOwnProperty(b)&&a.push(b);d="deleted"}b=0;for(var h=a.length;b<h;b++){if(l[a[b]])for(var c=0,j=l[a[b]].length;c<j;c++)l[a[b]][c](a[b],d);if(l["*"]){c=0;for(j=l["*"].length;c<j;c++)l["*"][c](a[b],d)}}}function e(){var a=
(+new Date).toString();"localStorage"==q||"globalStorage"==q?k.bStorage_update=a:"userDataBehavior"==q&&(f.setAttribute("bStorage_update",a),f.save("bStorage"));b()}function g(){if(k.bStorage)try{d=p.parse(String(k.bStorage))}catch(a){k.bStorage="{}"}else k.bStorage="{}";u=k.bStorage?String(k.bStorage).length:0;d.__bstorage_meta||(d.__bstorage_meta={});d.__bstorage_meta.CRC32||(d.__bstorage_meta.CRC32={})}function i(){if(d.__bstorage_meta.PubSub){for(var a=+new Date-2E3,b=0,c=d.__bstorage_meta.PubSub.length;b<
c;b++)if(d.__bstorage_meta.PubSub[b][0]<=a){d.__bstorage_meta.PubSub.splice(b,d.__bstorage_meta.PubSub.length-b);break}d.__bstorage_meta.PubSub.length||delete d.__bstorage_meta.PubSub}try{k.bStorage=p.stringify(d),f&&(f.setAttribute("bStorage",k.bStorage),f.save("bStorage")),u=k.bStorage?String(k.bStorage).length:0}catch(h){}}function m(a){if(!a||"string"!=typeof a&&"number"!=typeof a)throw new TypeError("Key name must be string or numeric");if("__bstorage_meta"==a)throw new TypeError("Reserved key name");
return!0}function o(){var a,b,h,j,p=Infinity,g=!1,f=[];clearTimeout(x);if(d.__bstorage_meta&&"object"==typeof d.__bstorage_meta.TTL){a=+new Date;h=d.__bstorage_meta.TTL;j=d.__bstorage_meta.CRC32;for(b in h)h.hasOwnProperty(b)&&(h[b]<=a?(delete h[b],delete j[b],delete d[b],g=!0,f.push(b)):h[b]<p&&(p=h[b]));Infinity!=p&&(x=setTimeout(o,p-a));g&&(i(),e(),c(f,"deleted"))}}function j(){var a;if(d.__bstorage_meta.PubSub){var b,h=v;for(a=d.__bstorage_meta.PubSub.length-1;0<=a;a--)if(b=d.__bstorage_meta.PubSub[a],
b[0]>v){var h=b[0],c=b[1];b=b[2];if(s[c])for(var j=0,e=s[c].length;j<e;j++)s[c][j](c,p.parse(p.stringify(b)))}v=h}}var h=window.jQuery||window.$||(window.$={}),p={parse:window.JSON&&(window.JSON.parse||window.JSON.decode)||window.__JSON&&window.__JSON.parse||__JSON&&__JSON.parse||String.prototype.evalJSON&&function(a){return String(a).evalJSON()}||h.parseJSON||h.evalJSON,stringify:Object.toJSON||window.JSON&&(window.JSON.stringify||window.JSON.encode)||window.__JSON&&window.__JSON.stringify||__JSON&&
__JSON.stringify||h.toJSON};if(!p.parse||!p.stringify)throw Error("No JSON support found, include //cdnjs.cloudflare.com/ajax/libs/json2/20110223/json2.js to page");var d={__bstorage_meta:{CRC32:{}}},k={bStorage:"{}"},f=null,u=0,q=!1,l={},n=!1,r=0,s={},v=+new Date,x,w={isXML:function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?"HTML"!==a.nodeName:!1},encode:function(a){if(!this.isXML(a))return!1;try{return(new XMLSerializer).serializeToString(a)}catch(b){try{return a.xml}catch(d){}}return!1},
decode:function(a){var b="DOMParser"in window&&(new DOMParser).parseFromString||window.ActiveXObject&&function(a){var b=new ActiveXObject("Microsoft.XMLDOM");b.async="false";b.loadXML(a);return b};if(!b)return!1;a=b.call("DOMParser"in window&&new DOMParser||window,a,"text/xml");return this.isXML(a)?a:!1}};BoxeverStorage={version:"0.4.3",set:function(a,b,h){m(a);h=h||{};if("undefined"==typeof b)return this.deleteKey(a),b;if(w.isXML(b))b={_is_xml:!0,xml:w.encode(b)};else{if("function"==typeof b)return;
b&&"object"==typeof b&&(b=p.parse(p.stringify(b)))}d[a]=b;for(var j=d.__bstorage_meta.CRC32,e=p.stringify(b),g=e.length,f=2538058380^g,i=0,k;4<=g;)k=e.charCodeAt(i)&255|(e.charCodeAt(++i)&255)<<8|(e.charCodeAt(++i)&255)<<16|(e.charCodeAt(++i)&255)<<24,k=1540483477*(k&65535)+((1540483477*(k>>>16)&65535)<<16),k^=k>>>24,k=1540483477*(k&65535)+((1540483477*(k>>>16)&65535)<<16),f=1540483477*(f&65535)+((1540483477*(f>>>16)&65535)<<16)^k,g-=4,++i;switch(g){case 3:f^=(e.charCodeAt(i+2)&255)<<16;case 2:f^=
(e.charCodeAt(i+1)&255)<<8;case 1:f^=e.charCodeAt(i)&255,f=1540483477*(f&65535)+((1540483477*(f>>>16)&65535)<<16)}f^=f>>>13;f=1540483477*(f&65535)+((1540483477*(f>>>16)&65535)<<16);j[a]="2."+((f^f>>>15)>>>0);this.setTTL(a,h.TTL||0);c(a,"updated");return b},get:function(a,b){m(a);return a in d?d[a]&&"object"==typeof d[a]&&d[a]._is_xml?w.decode(d[a].xml):d[a]:"undefined"==typeof b?null:b},deleteKey:function(a){m(a);return a in d?(delete d[a],"object"==typeof d.__bstorage_meta.TTL&&a in d.__bstorage_meta.TTL&&
delete d.__bstorage_meta.TTL[a],delete d.__bstorage_meta.CRC32[a],i(),e(),c(a,"deleted"),!0):!1},setTTL:function(a,b){var h=+new Date;m(a);b=Number(b)||0;return a in d?(d.__bstorage_meta.TTL||(d.__bstorage_meta.TTL={}),0<b?d.__bstorage_meta.TTL[a]=h+b:delete d.__bstorage_meta.TTL[a],i(),o(),e(),!0):!1},getTTL:function(a){var b=+new Date;m(a);return a in d&&d.__bstorage_meta.TTL&&d.__bstorage_meta.TTL[a]?(a=d.__bstorage_meta.TTL[a]-b)||0:0},flush:function(){d={__bstorage_meta:{CRC32:{}}};i();e();c(null,
"flushed");return!0},storageObj:function(){function a(){}a.prototype=d;return new a},index:function(){var a=[],b;for(b in d)d.hasOwnProperty(b)&&"__bstorage_meta"!=b&&a.push(b);return a},storageSize:function(){return u},currentBackend:function(){return q},storageAvailable:function(){return!!q},listenKeyChange:function(a,b){m(a);l[a]||(l[a]=[]);l[a].push(b)},stopListening:function(a,b){m(a);if(l[a])if(b)for(var d=l[a].length-1;0<=d;d--)l[a][d]==b&&l[a].splice(d,1);else delete l[a]},subscribe:function(a,
b){a=(a||"").toString();if(!a)throw new TypeError("Channel not defined");s[a]||(s[a]=[]);s[a].push(b)},publish:function(a,b){a=(a||"").toString();if(!a)throw new TypeError("Channel not defined");d.__bstorage_meta||(d.__bstorage_meta={});d.__bstorage_meta.PubSub||(d.__bstorage_meta.PubSub=[]);d.__bstorage_meta.PubSub.unshift([+new Date,a,b]);i();e()},reInit:function(){a()}};a:{h=!1;if("localStorage"in window)try{window.localStorage.setItem("_tmptest","tmpval"),h=!0,window.localStorage.removeItem("_tmptest")}catch(y){}if(h)try{window.localStorage&&
(k=window.localStorage,q="localStorage",r=k.bStorage_update)}catch(z){}else if("globalStorage"in window)try{window.globalStorage&&(k="localhost"==window.location.hostname?window.globalStorage["localhost.localdomain"]:window.globalStorage[window.location.hostname],q="globalStorage",r=k.bStorage_update)}catch(A){}else if(f=document.createElement("link"),f.addBehavior){f.style.behavior="url(#default#userData)";document.getElementsByTagName("head")[0].appendChild(f);try{f.load("bStorage")}catch(B){f.setAttribute("bStorage",
"{}"),f.save("bStorage"),f.load("bStorage")}h="{}";try{h=f.getAttribute("bStorage")}catch(C){}try{r=f.getAttribute("bStorage_update")}catch(D){}k.bStorage=h;q="userDataBehavior"}else{f=null;break a}g();o();"localStorage"==q||"globalStorage"==q?"addEventListener"in window?window.addEventListener("storage",b,!1):document.attachEvent("onstorage",b):"userDataBehavior"==q&&setInterval(b,1E3);j();"addEventListener"in window&&window.addEventListener("pageshow",function(a){a.persisted&&b()},!1)}})();
var BoxeverXML={isXML:function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?"HTML"!==a.nodeName:!1},string2xml:function(a){if(window.ActiveXObject){var b=new ActiveXObject("Microsoft.XMLDOM");b.async="false";b.loadXML(a)}else b=(new DOMParser).parseFromString(a,"text/xml");return b},xml2string:function(a){var b=a.documentElement;return void 0==b.xml?(new XMLSerializer).serializeToString(a):b.xml},unescape:function(a){a=a.replace(/&lt;/gi,"<");a=a.replace(/&gt;/gi,">");a=a.replace(/&quot;/gi,
'"');return a=a.replace(/&amp;/gi,"&")}},BoxeverJSONP={exec:function(a,b){var c="jsonp"+(100*Math.random()).toString(),c=c.replace(/\./g,""),a=a.replace("callback=?","callback="+c),a=a.replace("cb=?","cb="+c);window[c]=function(a){try{var g=document.getElementById(c);g.parentNode.removeChild(g)}catch(i){}"string"===typeof a&&(a=BoxeverXML.unescape(a),window.DOMParser?a=(new DOMParser).parseFromString(a,"text/xml"):(g=new ActiveXObject("Microsoft.XMLDOM"),g.async=!1,g.loadXML(a),a=g));b(a);try{window[c]=
null,delete window[c]}catch(m){}};document.getElementsByTagName("head")[0].appendChild(function(){var b=document.createElement("script");b.type="text/javascript";b.charset="UTF-8";b.src=a;b.async=!0;b.id=c;return b}())}},BoxeverJERS=BoxeverJERS||{errors:[]};
(function(){function a(a){var e=c+"/boxever-log-js-error.js?client_key="+b+"&message="+encodeURIComponent(a);document.getElementsByTagName("head")[0].appendChild(function(){var a=document.createElement("script");a.type="text/javascript";a.charset="UTF-8";a.src=e;return a}())}var b="cap9kylkxexvqbwfljqctlwjpvukqvde",c="https://api-ap-southeast-2-production.boxever.com/v1.2",e=BoxeverJERS.errors;BoxeverJERS.errors={push:function(){for(var b=0;b<arguments.length;b++)try{if("function"===typeof arguments[b])arguments[b]();
else{var c=arguments[b],e={};"string"===typeof c?e.message=c:(e.name="undefined"!==typeof c.name&&null!==c.name?c.name.toString():"",e.message="undefined"!==typeof c.message&&null!==c.message?c.message:"",e.stack="undefined"!==typeof c.stack&&null!==c.stack?c.stack:"");e.parent_url=document.location.href;var o=__JSON.stringify(e);a(o)}}catch(j){o={message:"Unknown error occured sending error report"},o=__JSON.stringify(o),a(o)}}};if("[object Array]"===Object.prototype.toString.call(e)&&(BoxeverJERS.errors.push.apply(BoxeverJERS.errors,
e),"undefined"!==typeof BoxeverJERS.settings&&("undefined"!==typeof BoxeverJERS.settings.client_key&&(b=BoxeverJERS.settings.client_key),"undefined"!==typeof BoxeverJERS.settings.client_key)))c=BoxeverJERS.settings.target})();var _boxever_error_service=_boxever_error_service||{errors:[]};(function(){var a=_boxever_error_service.errors;"[object Array]"===Object.prototype.toString.call(a)&&BoxeverJERS.errors.push.apply(BoxeverJERS.errors,a);_boxever_error_service=BoxeverJERS})();
var BoxeverCrossDomain=BoxeverCrossDomain||function(){var a,b,c=1,e,g=this;return{postMessage:function(a,b,e){b&&(e=e||parent,g.postMessage?e.postMessage(a,b.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):b&&(e.location=b.replace(/#.*$/,"")+"#"+ +new Date+c++ +"&"+a))},receiveMessage:function(c,m){g.postMessage?(e&&(g.removeEventListener?g.removeEventListener("message",e,!1):g.detachEvent("onmessage",e)),c&&(e=function(a){if("string"===typeof m&&a.origin!==m||"[object Function]"===Object.prototype.toString.call(m)&&
!1===m(a.origin))return!1;c(a)},g.addEventListener?g.addEventListener("message",e,!1):g.attachEvent("onmessage",e))):(a&&clearInterval(a),a=null,c&&(a=setInterval(function(){var a=document.location.hash,j=/^#?\d+&/;a!==b&&j.test(a)&&(b=a,c({data:a.replace(j,"")}))},100)))}}}(),_boxeverq=_boxeverq||[],_boxever_settings=_boxever_settings||{};
function __boxever(){this.client_key="cap9kylkxexvqbwfljqctlwjpvukqvde";this.target="https://api-ap-southeast-2-production.boxever.com/v1.2";this.cookie_name="bid_cap9kylkxexvqbwfljqctlwjpvukqvde";this.cookie_domain=".cebupacificair.com";this.cookie_path="/";this.cookie_expires_days=730;this.browser_id="anonymous";this.cross_domain_origin="https://api-ap-southeast-2-production.boxever.com";this.cross_domain_url="https://api-ap-southeast-2-production.boxever.com/v1.2/boxever-cross-domain.html";this.token_counter=
1;this.proxy_url="boxever-proxy.html";this.token=0;this.event=null;this.flag_ttl=24E5;__boxeverQueue=function(){this.push=function(){for(var a=0;a<arguments.length;a++)try{if("function"===typeof arguments[a])arguments[a]()}catch(b){BoxeverJERS.errors.push(b)}}};this.setCookie=function(a,b,c){b=encodeURI(b);if("undefined"!==typeof c&&null!==c){var e=new Date;e.setDate(e.getDate()+c);b=b+"; expires="+e.toUTCString()}b=b+"; path="+this.cookie_path;"undefined"!==typeof this.cookie_domain&&(null!==this.cookie_domain&&
0<this.cookie_domain.length)&&(b=b+"; domain="+this.cookie_domain);document.cookie=a+"="+b};this.getCookie=function(a){var b,c,e,g=document.cookie.split(";");for(b=0;b<g.length;b++)if(c=g[b].substr(0,g[b].indexOf("=")),e=g[b].substr(g[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c==a)return e=decodeURI(e)};this.storage=null;this.consoleLogData=function(){};this.getID=function(){return this.browser_id};this.getClientKey=function(){return this.client_key};this.getTarget=function(a){return a?this.target.replace("v1.2",
"v"+a):this.target};this.getCookieName=function(){return this.cookie_name};this.getCookieDomain=function(){return this.cookie_domain};this.getCookiePath=function(){return this.cookie_path};this.getCookieExpiresDays=function(){return this.cookie_expires_days};this.reset=function(){_boxeverq=[];this.storage&&this.storage.removeItem(this.cookie_name);this.init()};this.getURLParameter=function(a){return decodeURIComponent((RegExp("[?|&]"+a+"=([^&;]+?)(&|#|;|$)").exec(location.search)||[,""])[1].replace(/\+/g,
"%20"))||null};this.checkCookieEnabled=function(){var a=!1;try{this.setCookie("boxever_test","text_value",1),a="text_value"==this.getCookie("boxever_test"),this.setCookie("boxever_test","text_value",-1)}catch(b){}return a};this.checkStorageEnabled=function(){return BoxeverStorage.storageAvailable()};this.initRegular=function(){var a=this.storage.getItem(this.cookie_name);void 0!=a&&null!=a&&0<a.length?(this.storage.setItem(this.cookie_name,a,this.cookie_expires_days),this.browser_id=a,a=_boxeverq,
_boxeverq=new __boxeverQueue,_boxeverq.push.apply(_boxeverq,a)):this.browserCreate("{}",function(a){try{void 0!=a&&void 0!=a.ref&&(_boxever.browser_id=a.ref,_boxever.storage.setItem(_boxever.cookie_name,_boxever.browser_id,_boxever.cookie_expires_days),a=_boxeverq,_boxeverq=new __boxeverQueue,_boxeverq.push.apply(_boxeverq,a))}catch(c){throw BoxeverJERS.errors.push(c),c;}},"json")};this.addUTMParams=function(a){var b;try{decodeURIComponent(window.location.search),b=decodeURIComponent}catch(c){try{unescape(window.location.search),
b=unescape}catch(e){}}if(b){for(var g,i=/\+/g,m=/([^&=]+)=?([^&]*)/g,o=window.location.search.substring(1),j={};g=m.exec(o);)j[b(g[1].replace(i," "))]=b(g[2].replace(i," "));for(var h in j)if(0==h.indexOf("utm_")||0==h.indexOf("UTM_")||"b_cer"===h||"utr"===h)a[h]=j[h]}return a};this.callIfFlagIsFalse=function(a,b,c){var e=!1;this.checkStorageEnabled()&&(e=BoxeverStorage.get(a,!1));try{if(!e&&(b(),this.checkStorageEnabled())){var g=this.flag_ttl;void 0!==c&&(g=c);BoxeverStorage.set(a,!0,{TTL:g})}}catch(i){BoxeverJERS.errors.push(i)}};
this.eventPublish=function(a,b){var c=this.proxy_url+"?token="+this.token_counter+"&baseUrl=https://api-ap-southeast-2-production.boxever.com&version=1.2&client_key=cap9kylkxexvqbwfljqctlwjpvukqvde&event="+encodeURIComponent(__JSON.stringify(a));this.token_counter++;var e=document.createElement("iframe");e.style.display="none";e.width="0";e.height="0";e.src=c;document.body.appendChild(e);b()};this.isCookied=function(){var a=this.storage.getItem(this.cookie_name);return void 0!=a&&null!=a&&0<a.length};
this.consume=function(){1<this.token&&this.initRegular()};this.onCookieConsume=function(){_boxever.isCookied()?_boxever.consume():setTimeout(function(){_boxever.onCookieConsume()},10)};this.initConsumer=function(){var a=this.getURLParameter("token"),b=this.getURLParameter("event");if("undefined"!==typeof a&&null!=a&&"undefined"!==typeof b&&null!=b)if(this.token=a,this.event=__JSON.parse(b),_boxeverq.push(function(){_boxever.event.browser_id=_boxever.getID();_boxever.eventCreate(_boxever.event,function(){},
"json")}),1==a)this.initRegular();else this.onCookieConsume();else BoxeverJERS.errors.push("consumer token or event is undefined or null")};this.initPublisher=function(){this.eventCreate=this.eventPublish;var a=_boxeverq;_boxeverq=new __boxeverQueue;_boxeverq.push.apply(_boxeverq,a)};this.initCrossDomain=function(){var a=this.getCookie(this.cookie_name);if(void 0!=a&&null!=a&&0<a.length)this.browser_id=a,a=_boxeverq,_boxeverq=new __boxeverQueue,_boxeverq.push.apply(_boxeverq,a);else if(this.checkCookieEnabled()){var a=
this.cross_domain_origin,b=this.cross_domain_url,b=b+"?",b=b+"client_key="+encodeURIComponent(this.getClientKey()),b=b+"&",b=b+"parent_url="+encodeURIComponent(window.location);BoxeverCrossDomain.receiveMessage(function(a){try{void 0!=a&&(void 0!=a.data&&"string"==typeof a.data&&36==a.data.length)&&(_boxever.browser_id=a.data,_boxever.setCookie(_boxever.getCookieName(),a.data),a=_boxeverq,_boxeverq=new __boxeverQueue,_boxeverq.push.apply(_boxeverq,a))}catch(b){throw BoxeverJERS.errors.push(b),b;}},
a);document.getElementsByTagName("body")[0].appendChild(function(){var a=document.createElement("iframe");a.style.cssText="visibility:hidden;display:none";a.width=0;a.height=0;a.src=b;return a}())}};this.initSettings=function(){"undefined"!==typeof _boxever_settings.client_key&&(this.client_key=_boxever_settings.client_key,this.cookie_name="bid_"+_boxever_settings.client_key);"undefined"!==typeof _boxever_settings.target&&(this.target=_boxever_settings.target);"undefined"!==typeof _boxever_settings.cookie_domain&&
(this.cookie_domain=_boxever_settings.cookie_domain);this.checkCookieEnabled()?this.storage={setItem:function(a,b,c){_boxever.setCookie(a,b,c)},getItem:function(a){return _boxever.getCookie(a)},removeItem:function(a){_boxever.setCookie(a,"",-1);return true}}:this.checkStorageEnabled()&&(this.storage={setItem:function(a,b,c){BoxeverStorage.set(a,b,c)},getItem:function(a,b){return BoxeverStorage.get(a,b)},removeItem:function(a){return BoxeverStorage.deleteKey(a)}});if("undefined"!=typeof _boxever_settings.publisher)"undefined"!=
typeof _boxever_settings.publisher.url&&(this.proxy_url=_boxever_settings.publisher.url);else if("undefined"!==typeof _boxever_settings.cross_domain&&("undefined"!=typeof _boxever_settings.cross_domain.origin&&(this.cross_domain_origin=_boxever_settings.cross_domain.origin),"undefined"!=typeof _boxever_settings.cross_domain.url))this.cross_domain_url=_boxever_settings.cross_domain.url};this.init=function(){try{if(this.initSettings(),this.storage||"undefined"!=typeof _boxever_settings.publisher)"undefined"!=
typeof _boxever_settings.publisher?this.initPublisher():"undefined"!=typeof _boxever_settings.consumer?this.initConsumer():"undefined"!==typeof _boxever_settings.cross_domain?this.initCrossDomain():this.initRegular()}catch(a){throw BoxeverJERS.errors.push(a),a;}}}var Boxever=Boxever||new __boxever;
(function(a){a.get=function(a,c){""===c&&(c="BoxeverUtils.consoleLogData");BoxeverJSONP.exec(a+"&callback=?",c)};a.post=function(a,c,e){""===e&&(e="BoxeverUtils.consoleLogData");var g="",g=BoxeverXML.isXML(c)?BoxeverXML.xml2string(c):"string"===typeof c&&"<"==c.charAt(0)?c:"string"===typeof c&&"{"==c.charAt(0)?__JSON.stringify(__JSON.parse(c)):__JSON.stringify(c),a=-1==a.indexOf("?")?a+"?":a+"&",a=a+"message="+encodeURIComponent(g)+"&callback=?";BoxeverJSONP.exec(a,e)}})(Boxever);
(function(a,b){function c(c,h,e,d,g,f){var i=a.getTarget(),i=i+"/"+c+"/create."+d+"?client_key="+b;"undefined"!=typeof g&&(i=i+"&boxever_version="+g);"undefined"!=typeof f&&(i=i+"&content_version="+f);a.post(i,h,e)}function e(c,h,e,d,g){var f=a.getTarget(),f=f+"/"+c+"/create."+g+"?client_key="+b;a.post(f+"&api_token="+e,h,d)}function g(c,h,e,d,g){var f=a.getTarget(),f=f+"/"+c+"/"+h+"/show."+g+"?client_key="+b;a.get(f+"&api_token="+e,d)}function i(c,h,e,d,g){var f=a.getTarget(),f=f+"/"+c+"/search."+
g+"?client_key="+b,f=f+"&api_token="+e;null!==h&&0<h.indexOf("=")&&(e=h.indexOf("="),c=encodeURIComponent(h.substring(0,e)),h=encodeURIComponent(h.substring(e).replace("=","")),f=f+"&"+c+"="+h);a.get(f,d)}function m(c,h,e,d,g,f){var i=a.getTarget(),i=i+"/"+c+"/"+h+"/update."+f+"?client_key="+b;a.post(i+"&api_token="+d,e,g)}function o(c,h,e,d,g,f){var i=a.getTarget(),i=i+"/"+c+"/"+h;null!==e&&0<e.length&&(i=i+"/"+encodeURIComponent(e));i=i+"/delete."+f+"?client_key="+b;a.get(i+"&api_token="+d,g)}a.pingCreate=
function(a,b,e){c("ping",a,b,e)};a.eventCreate=function(a,b,e){c("event",a,b,e,"eefc95721c5eb49559869b2c95d65fb8","undefined"!=typeof _boxever_content_version?_boxever_content_version:void 0)};a.eventShow=function(a,b,c,d){g("event",a,b,c,d)};a.eventSearch=function(a,b,c,d){i("event",a,b,c,d)};a.browserCreate=function(a,b,e){c("browser",a,b,e)};a.browserShow=function(a,b,c,d){g("browser",a,b,c,d)};a.customerCreate=function(a,b,c,d){e("customer",a,b,c,d)};a.customerShow=function(a,b,c,d){g("customer",
a,b,c,d)};a.customerUpdate=function(a,b,c,d,e){m("customer",a,b,c,d,e)};a.customerDelete=function(a,b,c,d,e){o("customer",a,b,c,d,e)};a.customerSearch=function(a,b,c,d){i("customer",a,b,c,d)};a.customerDataCreate=function(a,b,c,d){e("customerdata",a,b,c,d)};a.customerDataShow=function(a,b,c,d){g("customerdata",a,b,c,d)};a.customerDataUpdate=function(a,b,c,d,e){m("customerdata",a,b,c,d,e)};a.customerDataDelete=function(a,b,c,d,e){o("customerdata",a,b,c,d,e)};a.campaignCreate=function(a,b,e){c("campaign",
a,b,e)};a.campaignShow=function(a,b,c){g("campaign",ref,api_token,b,c)};a.campaignSearch=function(a,b,c,d){i("campaign",a,b,c,d)};a.profileCreate=function(a,b,e,d){c("profile",a,e,d)};a.profileShow=function(a,b,c,d){g("profile",a,b,c,d)};a.profileUpdate=function(a,b,c,d,e){m("profile",b,a,c,d,e)};a.profileSearch=function(a,b,c,d){i("profile",a,b,c,d)}})(Boxever,"cap9kylkxexvqbwfljqctlwjpvukqvde");
(function(a){a.flowExecutionCreate=function(b,c){var e=a.getTarget("2");a.post(e+"/flowExecutions",b,c)}})(Boxever);var _boxever=Boxever;_boxever.init();
